### Importing libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
# Models
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor

### Reading Data

In [5]:
data=pd.read_csv('data/StudentsPerformance.csv')
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

### Preparing X and Y Variables

In [19]:
# axis=0 (rows)
# Think:
# “I am removing data points”
# axis=1 (columns)
# Think:
# “I am removing features”

X=data.drop(columns=['math score'])
y=data['math score']
X.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75

In [ ]:
# Creating Column Transformer which converts the transformation in a pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

num_feature=X.select_dtypes(exclude='object').columns
cat_features=X.select_dtypes(include='object').columns

num_transformer=StandardScaler()
cat_transformer=OneHotEncoder()

preprocessor=ColumnTransformer(
    [
        ('OneHotEncoder', cat_transformer, cat_features),
        ('StandardScaler', num_transformer, num_feature)
    ]
)

In [ ]:
X=preprocessor.fit_transform(X)

### Separate DataSet into Training data nd Test Data

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25, random_state=42)
X_train.shape, X_test.shape

((750, 19), (250, 19))

### Function to give all metrics for the model after training

In [36]:
def evaluate(true, predicted):
    mse=mean_squared_error(true,predicted)
    mae=mean_absolute_error(true,predicted)
    rmse=np.sqrt(mse)
    r2_sc=r2_score(true,predicted)
    return mae, rmse, r2_sc

In [37]:
print(type(X_train))
print(X_train.shape)

print(type(X_train[0]))

<class 'numpy.ndarray'>
(750, 19)
<class 'numpy.ndarray'>

In [43]:
# Creating all Models
models={
    'Linear Regression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'K-Nearest Neighbor Regressor':KNeighborsRegressor(),
    'Decision Tree':DecisionTreeRegressor(),
    'Random Forest':RandomForestRegressor(),
    'XG Boost Regressor':XGBRegressor(),
    'Cat Boost Regressor':CatBoostRegressor(),
    'AdaBoost Regressor':AdaBoostRegressor()
}
model_list=[]
r2_list=[]
rmse_list=[]

for name, model in models.items():
    model.fit(X_train, y_train)  # Model Training

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate
    model_train_mae, model_train_rmse, model_train_r2Score = evaluate(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2Score = evaluate(y_test, y_test_pred)

    print(name)
    model_list.append(model)
    r2_list.append(model_test_r2Score)
    rmse_list.append(model_test_rmse)

    print("Model performance for Training set")
    print(f"- Root Mean Squared Error: {model_train_rmse:.4f}")
    print(f"- Mean Absolute Error: {model_train_mae:.4f}")
    print(f"- R2 Score: {model_train_r2Score:.4f}")

    print("-" * 30)

    print("Model performance for Test set")
    print(f"- Root Mean Squared Error: {model_test_rmse:.4f}")
    print(f"- Mean Absolute Error: {model_test_mae:.4f}")
    print(f"- R2 Score: {model_test_r2Score:.4f}")

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 5.2972
- Mean Absolute Error: 4.2383
- R2 Score: 0.8743
------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.4825
- Mean Absolute Error: 4.3379
- R2 Score: 0.8778
Lasso
Model performance for Training set
- Root Mean Squared Error: 6.5515
- Mean Absolute Error: 5.1837
- R2 Score: 0.8077
------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.6541
- Mean Absolute Error: 5.2217
- R2 Score: 0.8200
Ridge
Model performance for Training set
- Root Mean Squared Error: 5.2976
- Mean Absolute Error: 4.2368
- R2 Score: 0.8743
------------------------------
Model performance for Test set
- Root Mean Squared Error: 5.4788
- Mean Absolute Error: 4.3354
- R2 Score: 0.8780
K-Nearest Neighbor Regressor
Model performance for Training set
- Root Mean Squared Error: 5.7920
- Mean Absolute Error: 4.5864
- R2 Score: 0.8497
------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.1327
- Mean Absolute Error: 5.5208
- R2 Score: 0.7932
Decision Tree
Model performance for Training set
- Root Mean Squared Error: 0.2887
- Mean Absolute Error: 0.0200
- R2 Score: 0.9996
------------------------------
Model performance for Test set
- Root Mean Squared Error: 7.7017
- Mean Absolute Error: 6.0440
- R2 Score: 0.7589
Random Forest
Model performance for Training set
- Root Mean Squared Error: 2.2629
- Mean Absolute Error: 1.8082
- R2 Score: 0.9771
------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.1076
- Mean Absolute Error: 4.7533
- R2 Score: 0.8484
XG Boost Regressor
Model performance for Training set
- Root Mean Squared Error: 0.8783
- Mean Absolute Error: 0.5772
- R2 Score: 0.9965
------------------------------
Model performance for Test set
- Root Mean Squared Error: 6.3464
- Mean Absolute Error: 4.9605
- R2 Score: 0.8363
Learning rate set to 0.039124
0:	learn: 14.5605246	total: 1.02ms	remaining: 1.02s
1:	learn: 14.1876312	total: 1.61ms	remaining: 803ms
2:	learn: 13.8256484	total: 2.24ms	remaining: 745ms
3:	learn: 13.4648661	total: 2.82ms	remaining: 702ms
4:	learn: 13.1329085	total: 3.45ms	remaining: 687ms
5:	learn: 12.8141173	total: 4.07ms	remaining: 674ms
6:	learn: 12.5102520	total: 4.7ms	remaining: 667ms
7:	learn: 12.2389061	total: 5.33ms	remaining: 660ms
8:	learn: 11.9602412	total: 6.04ms	remaining: 665ms
9:	learn: 11.6751219	total: 6.68ms	remaining: 661ms
10:	learn: 11.4082110	total: 7.66ms	remaining: 689ms
11:	learn: 11.1696037	total: 8.49ms	remaining: 699ms
12:	learn: 10.9303033	total: 9.06ms	remaining: 688ms
13:	learn: 10.7392447	total: 9.61ms	remaining: 677ms
14:	learn: 10.5017979	total: 10.2ms	remaining: 668ms
15:	learn: 10.3065756	total: 10.7ms	remaining: 661ms
16:	learn: 10.1050143	total: 11.3ms	remaining: 655ms
17:	learn: 9.8908889	total: 11.9ms	remaining: 649ms
18:	learn: 9.7014402	total: 12.4ms	remaining: 641ms
19:	learn: 9.5071843	total: 13ms	remaining: 638ms
20:	learn: 9.3573776	total: 13.6ms	remaining: 632ms
21:	learn: 9.1784990	total: 14.3ms	remaining: 634ms
22:	learn: 9.0009881	total: 15ms	remaining: 639ms
23:	learn: 8.8432095	total: 15.7ms	remaining: 640ms
24:	learn: 8.6939759	total: 16.4ms	remaining: 638ms
25:	learn: 8.5462745	total: 17ms	remaining: 637ms
26:	learn: 8.4203437	total: 17.6ms	remaining: 635ms
27:	learn: 8.2813790	total: 18.2ms	remaining: 631ms
28:	learn: 8.1422244	total: 18.8ms	remaining: 629ms
29:	learn: 8.0177861	total: 19.4ms	remaining: 627ms
30:	learn: 7.8939827	total: 20ms	remaining: 624ms
31:	learn: 7.7741020	total: 20.6ms	remaining: 623ms
32:	learn: 7.6719873	total: 21.3ms	remaining: 624ms
33:	learn: 7.5698098	total: 22.1ms	remaining: 628ms
34:	learn: 7.4715802	total: 22.8ms	remaining: 630ms
35:	learn: 7.3745976	total: 23.4ms	remaining: 627ms
36:	learn: 7.2855330	total: 24ms	remaining: 624ms
37:	learn: 7.2041006	total: 24.6ms	remaining: 623ms
38:	learn: 7.1173536	total: 25.2ms	remaining: 621ms
39:	learn: 7.0418552	total: 25.7ms	remaining: 618ms
40:	learn: 6.9569846	total: 26.3ms	remaining: 615ms
41:	learn: 6.8846452	total: 26.9ms	remaining: 613ms
42:	learn: 6.8066394	total: 27.5ms	remaining: 612ms
43:	learn: 6.7526310	total: 28.1ms	remaining: 610ms
44:	learn: 6.6923070	total: 28.8ms	remaining: 611ms
45:	learn: 6.6223544	total: 29.5ms	remaining: 612ms
46:	learn: 6.5725516	total: 30.2ms	remaining: 612ms
47:	learn: 6.5117912	total: 30.8ms	remaining: 610ms
48:	learn: 6.4562033	total: 31.4ms	remaining: 608ms
49:	learn: 6.4079488	total: 32ms	remaining: 607ms
50:	learn: 6.3541749	total: 32.6ms	remaining: 606ms
51:	learn: 6.3071879	total: 33.2ms	remaining: 606ms
52:	learn: 6.2595100	total: 33.9ms	remaining: 605ms
53:	learn: 6.2155436	total: 34.4ms	remaining: 603ms
54:	learn: 6.1739727	total: 35.1ms	remaining: 603ms
55:	learn: 6.1370686	total: 35.7ms	remaining: 602ms
56:	learn: 6.0941227	total: 36.4ms	remaining: 602ms
57:	learn: 6.0633907	total: 37ms	remaining: 601ms
58:	learn: 6.0280407	total: 37.7ms	remaining: 602ms
59:	learn: 5.9987746	total: 38.3ms	remaining: 600ms
60:	learn: 5.9664732	total: 38.9ms	remaining: 599ms
61:	learn: 5.9336183	total: 39.5ms	remaining: 597ms
62:	learn: 5.9034646	total: 40ms	remaining: 595ms
63:	learn: 5.8699759	total: 40.7ms	remaining: 595ms
64:	learn: 5.8449903	total: 41.5ms	remaining: 596ms
65:	learn: 5.8162324	total: 42.2ms	remaining: 598ms
66:	learn: 5.7935909	total: 43ms	remaining: 599ms
67:	learn: 5.7680120	total: 44ms	remaining: 603ms
68:	learn: 5.7452649	total: 44.9ms	remaining: 606ms
69:	learn: 5.7220450	total: 45.7ms	remaining: 607ms
70:	learn: 5.7013900	total: 46.5ms	remaining: 608ms
71:	learn: 5.6814489	total: 47.4ms	remaining: 611ms
72:	learn: 5.6601712	total: 48.2ms	remaining: 612ms
73:	learn: 5.6397176	total: 48.9ms	remaining: 612ms
74:	learn: 5.6224552	total: 49.6ms	remaining: 611ms
75:	learn: 5.6051834	total: 50.4ms	remaining: 612ms
76:	learn: 5.5906956	total: 51.3ms	remaining: 615ms
77:	learn: 5.5710763	total: 52.1ms	remaining: 616ms
78:	learn: 5.5526980	total: 52.9ms	remaining: 617ms
79:	learn: 5.5362165	total: 53.7ms	remaining: 617ms
80:	learn: 5.5210766	total: 54.3ms	remaining: 616ms
81:	learn: 5.5050638	total: 55.1ms	remaining: 617ms
82:	learn: 5.4903138	total: 55.8ms	remaining: 617ms
83:	learn: 5.4758145	total: 56.6ms	remaining: 617ms
84:	learn: 5.4611230	total: 57.3ms	remaining: 617ms
85:	learn: 5.4459208	total: 58.1ms	remaining: 618ms
86:	learn: 5.4345454	total: 59ms	remaining: 619ms
87:	learn: 5.4245909	total: 59.8ms	remaining: 619ms
88:	learn: 5.4123708	total: 60.6ms	remaining: 620ms
89:	learn: 5.3996950	total: 61.4ms	remaining: 621ms
90:	learn: 5.3870224	total: 62.2ms	remaining: 621ms
91:	learn: 5.3786391	total: 62.9ms	remaining: 620ms
92:	learn: 5.3661598	total: 63.6ms	remaining: 620ms
93:	learn: 5.3569756	total: 64.3ms	remaining: 620ms
94:	learn: 5.3469052	total: 65ms	remaining: 619ms
95:	learn: 5.3385944	total: 65.7ms	remaining: 619ms
96:	learn: 5.3285654	total: 66.6ms	remaining: 620ms
97:	learn: 5.3200704	total: 67.4ms	remaining: 620ms
98:	learn: 5.3105018	total: 68.1ms	remaining: 620ms
99:	learn: 5.3008855	total: 68.8ms	remaining: 619ms
100:	learn: 5.2903097	total: 69.6ms	remaining: 619ms
101:	learn: 5.2798955	total: 70.3ms	remaining: 619ms
102:	learn: 5.2715721	total: 71.1ms	remaining: 620ms
103:	learn: 5.2611684	total: 71.8ms	remaining: 619ms
104:	learn: 5.2494475	total: 72.7ms	remaining: 620ms
105:	learn: 5.2398581	total: 73.7ms	remaining: 622ms
106:	learn: 5.2278783	total: 74.6ms	remaining: 622ms
107:	learn: 5.2209532	total: 75.5ms	remaining: 623ms
108:	learn: 5.2145357	total: 76.2ms	remaining: 623ms
109:	learn: 5.2041854	total: 77ms	remaining: 623ms
110:	learn: 5.1969856	total: 77.6ms	remaining: 622ms
111:	learn: 5.1890261	total: 78.1ms	remaining: 620ms
112:	learn: 5.1813495	total: 78.7ms	remaining: 618ms
113:	learn: 5.1725103	total: 79.2ms	remaining: 615ms
114:	learn: 5.1658452	total: 79.8ms	remaining: 614ms
115:	learn: 5.1594325	total: 80.5ms	remaining: 613ms
116:	learn: 5.1517529	total: 81.2ms	remaining: 613ms
117:	learn: 5.1468963	total: 81.9ms	remaining: 612ms
118:	learn: 5.1395760	total: 82.5ms	remaining: 611ms
119:	learn: 5.1343139	total: 83.2ms	remaining: 610ms
120:	learn: 5.1317778	total: 83.5ms	remaining: 607ms
121:	learn: 5.1248686	total: 84.1ms	remaining: 605ms
122:	learn: 5.1203478	total: 84.6ms	remaining: 603ms
123:	learn: 5.1144893	total: 85.1ms	remaining: 601ms
124:	learn: 5.1083949	total: 85.6ms	remaining: 600ms
125:	learn: 5.1029286	total: 86.1ms	remaining: 598ms
126:	learn: 5.0992186	total: 86.7ms	remaining: 596ms
127:	learn: 5.0952170	total: 87.3ms	remaining: 595ms
128:	learn: 5.0888207	total: 88ms	remaining: 594ms
129:	learn: 5.0837457	total: 88.7ms	remaining: 593ms
130:	learn: 5.0782875	total: 89.3ms	remaining: 592ms
131:	learn: 5.0747994	total: 89.9ms	remaining: 591ms
132:	learn: 5.0664471	total: 90.5ms	remaining: 590ms
133:	learn: 5.0622772	total: 91ms	remaining: 588ms
134:	learn: 5.0591965	total: 91.6ms	remaining: 587ms
135:	learn: 5.0524178	total: 92.1ms	remaining: 585ms
136:	learn: 5.0473989	total: 92.6ms	remaining: 583ms
137:	learn: 5.0414506	total: 93.1ms	remaining: 582ms
138:	learn: 5.0386329	total: 93.6ms	remaining: 580ms
139:	learn: 5.0367957	total: 94.2ms	remaining: 578ms
140:	learn: 5.0330091	total: 94.9ms	remaining: 578ms
141:	learn: 5.0296082	total: 95.7ms	remaining: 578ms
142:	learn: 5.0271588	total: 96.4ms	remaining: 577ms
143:	learn: 5.0210815	total: 96.9ms	remaining: 576ms
144:	learn: 5.0152172	total: 97.5ms	remaining: 575ms
145:	learn: 5.0119101	total: 98.1ms	remaining: 574ms
146:	learn: 5.0029711	total: 98.6ms	remaining: 572ms
147:	learn: 4.9991862	total: 99.2ms	remaining: 571ms
148:	learn: 4.9943992	total: 99.7ms	remaining: 570ms
149:	learn: 4.9907084	total: 100ms	remaining: 568ms
150:	learn: 4.9861761	total: 101ms	remaining: 567ms
151:	learn: 4.9822722	total: 101ms	remaining: 565ms
152:	learn: 4.9775150	total: 102ms	remaining: 564ms
153:	learn: 4.9735990	total: 103ms	remaining: 564ms
154:	learn: 4.9667269	total: 103ms	remaining: 564ms
155:	learn: 4.9596195	total: 104ms	remaining: 563ms
156:	learn: 4.9509543	total: 105ms	remaining: 562ms
157:	learn: 4.9471784	total: 105ms	remaining: 561ms
158:	learn: 4.9437120	total: 106ms	remaining: 559ms
159:	learn: 4.9369004	total: 106ms	remaining: 558ms
160:	learn: 4.9295384	total: 107ms	remaining: 556ms
161:	learn: 4.9275846	total: 107ms	remaining: 555ms
162:	learn: 4.9246662	total: 108ms	remaining: 554ms
163:	learn: 4.9228308	total: 108ms	remaining: 552ms
164:	learn: 4.9167723	total: 109ms	remaining: 551ms
165:	learn: 4.9102134	total: 109ms	remaining: 550ms
166:	learn: 4.9063564	total: 110ms	remaining: 550ms
167:	learn: 4.9044134	total: 111ms	remaining: 549ms
168:	learn: 4.8979719	total: 111ms	remaining: 548ms
169:	learn: 4.8959490	total: 112ms	remaining: 547ms
170:	learn: 4.8866812	total: 113ms	remaining: 545ms
171:	learn: 4.8816928	total: 113ms	remaining: 544ms
172:	learn: 4.8761762	total: 114ms	remaining: 543ms
173:	learn: 4.8709530	total: 114ms	remaining: 542ms
174:	learn: 4.8647810	total: 115ms	remaining: 540ms
175:	learn: 4.8587239	total: 115ms	remaining: 539ms
176:	learn: 4.8558201	total: 116ms	remaining: 538ms
177:	learn: 4.8539504	total: 116ms	remaining: 537ms
178:	learn: 4.8503844	total: 118ms	remaining: 540ms
179:	learn: 4.8478124	total: 118ms	remaining: 540ms
180:	learn: 4.8448613	total: 119ms	remaining: 539ms
181:	learn: 4.8408913	total: 120ms	remaining: 537ms
182:	learn: 4.8341192	total: 120ms	remaining: 536ms
183:	learn: 4.8301413	total: 121ms	remaining: 535ms
184:	learn: 4.8266649	total: 121ms	remaining: 533ms
185:	learn: 4.8217926	total: 122ms	remaining: 532ms
186:	learn: 4.8191311	total: 122ms	remaining: 531ms
187:	learn: 4.8126796	total: 123ms	remaining: 530ms
188:	learn: 4.8062588	total: 123ms	remaining: 528ms
189:	learn: 4.8004737	total: 124ms	remaining: 527ms
190:	learn: 4.7934076	total: 124ms	remaining: 527ms
191:	learn: 4.7910603	total: 125ms	remaining: 526ms
192:	learn: 4.7886007	total: 126ms	remaining: 525ms
193:	learn: 4.7847203	total: 126ms	remaining: 524ms
194:	learn: 4.7803518	total: 127ms	remaining: 523ms
195:	learn: 4.7774693	total: 127ms	remaining: 522ms
196:	learn: 4.7739332	total: 128ms	remaining: 521ms
197:	learn: 4.7718397	total: 128ms	remaining: 519ms
198:	learn: 4.7672164	total: 129ms	remaining: 518ms
199:	learn: 4.7618410	total: 129ms	remaining: 517ms
200:	learn: 4.7578804	total: 130ms	remaining: 516ms
201:	learn: 4.7568620	total: 130ms	remaining: 514ms
202:	learn: 4.7532102	total: 131ms	remaining: 514ms
203:	learn: 4.7475034	total: 132ms	remaining: 514ms
204:	learn: 4.7408690	total: 132ms	remaining: 514ms
205:	learn: 4.7386044	total: 133ms	remaining: 513ms
206:	learn: 4.7336542	total: 134ms	remaining: 513ms
207:	learn: 4.7322384	total: 134ms	remaining: 512ms
208:	learn: 4.7275342	total: 135ms	remaining: 511ms
209:	learn: 4.7232089	total: 136ms	remaining: 511ms
210:	learn: 4.7164375	total: 136ms	remaining: 509ms
211:	learn: 4.7143760	total: 137ms	remaining: 508ms
212:	learn: 4.7095987	total: 137ms	remaining: 507ms
213:	learn: 4.7039154	total: 138ms	remaining: 506ms
214:	learn: 4.6999241	total: 138ms	remaining: 505ms
215:	learn: 4.6974396	total: 139ms	remaining: 504ms
216:	learn: 4.6929101	total: 140ms	remaining: 504ms
217:	learn: 4.6882864	total: 141ms	remaining: 504ms
218:	learn: 4.6856228	total: 141ms	remaining: 503ms
219:	learn: 4.6832353	total: 142ms	remaining: 502ms
220:	learn: 4.6785696	total: 142ms	remaining: 501ms
221:	learn: 4.6742824	total: 143ms	remaining: 500ms
222:	learn: 4.6720975	total: 143ms	remaining: 499ms
223:	learn: 4.6661892	total: 144ms	remaining: 498ms
224:	learn: 4.6634546	total: 144ms	remaining: 497ms
225:	learn: 4.6613042	total: 145ms	remaining: 496ms
226:	learn: 4.6575201	total: 145ms	remaining: 495ms
227:	learn: 4.6549288	total: 146ms	remaining: 494ms
228:	learn: 4.6512355	total: 147ms	remaining: 494ms
229:	learn: 4.6483413	total: 147ms	remaining: 493ms
230:	learn: 4.6448487	total: 148ms	remaining: 492ms
231:	learn: 4.6422400	total: 148ms	remaining: 491ms
232:	learn: 4.6413001	total: 149ms	remaining: 490ms
233:	learn: 4.6385881	total: 149ms	remaining: 489ms
234:	learn: 4.6353562	total: 150ms	remaining: 488ms
235:	learn: 4.6323109	total: 150ms	remaining: 487ms
236:	learn: 4.6280817	total: 151ms	remaining: 486ms
237:	learn: 4.6245370	total: 151ms	remaining: 485ms
238:	learn: 4.6207030	total: 152ms	remaining: 484ms
239:	learn: 4.6126109	total: 152ms	remaining: 483ms
240:	learn: 4.6121369	total: 153ms	remaining: 482ms
241:	learn: 4.6093948	total: 154ms	remaining: 481ms
242:	learn: 4.6048749	total: 154ms	remaining: 480ms
243:	learn: 4.6028159	total: 155ms	remaining: 480ms
244:	learn: 4.6002129	total: 156ms	remaining: 479ms
245:	learn: 4.5964970	total: 156ms	remaining: 479ms
246:	learn: 4.5915753	total: 157ms	remaining: 478ms
247:	learn: 4.5909175	total: 157ms	remaining: 477ms
248:	learn: 4.5872276	total: 158ms	remaining: 476ms
249:	learn: 4.5863121	total: 158ms	remaining: 475ms
250:	learn: 4.5823548	total: 159ms	remaining: 474ms
251:	learn: 4.5801245	total: 159ms	remaining: 473ms
252:	learn: 4.5781489	total: 160ms	remaining: 472ms
253:	learn: 4.5760434	total: 161ms	remaining: 471ms
254:	learn: 4.5751349	total: 161ms	remaining: 471ms
255:	learn: 4.5723972	total: 162ms	remaining: 470ms
256:	learn: 4.5668064	total: 163ms	remaining: 470ms
257:	learn: 4.5654896	total: 163ms	remaining: 469ms
258:	learn: 4.5633146	total: 164ms	remaining: 468ms
259:	learn: 4.5585485	total: 164ms	remaining: 468ms
260:	learn: 4.5551828	total: 165ms	remaining: 467ms
261:	learn: 4.5496342	total: 166ms	remaining: 466ms
262:	learn: 4.5469698	total: 166ms	remaining: 465ms
263:	learn: 4.5451694	total: 167ms	remaining: 464ms
264:	learn: 4.5448568	total: 167ms	remaining: 463ms
265:	learn: 4.5437454	total: 168ms	remaining: 462ms
266:	learn: 4.5392893	total: 168ms	remaining: 462ms
267:	learn: 4.5391048	total: 169ms	remaining: 461ms
268:	learn: 4.5370632	total: 169ms	remaining: 460ms
269:	learn: 4.5338936	total: 170ms	remaining: 460ms
270:	learn: 4.5319614	total: 171ms	remaining: 459ms
271:	learn: 4.5243869	total: 171ms	remaining: 459ms
272:	learn: 4.5200495	total: 172ms	remaining: 458ms
273:	learn: 4.5192348	total: 172ms	remaining: 457ms
274:	learn: 4.5181762	total: 173ms	remaining: 456ms
275:	learn: 4.5165519	total: 173ms	remaining: 455ms
276:	learn: 4.5105361	total: 174ms	remaining: 454ms
277:	learn: 4.5058770	total: 175ms	remaining: 453ms
278:	learn: 4.4998571	total: 175ms	remaining: 453ms
279:	learn: 4.4988786	total: 176ms	remaining: 452ms
280:	learn: 4.4933906	total: 177ms	remaining: 452ms
281:	learn: 4.4897442	total: 177ms	remaining: 451ms
282:	learn: 4.4864125	total: 178ms	remaining: 451ms
283:	learn: 4.4793953	total: 178ms	remaining: 450ms
284:	learn: 4.4770121	total: 179ms	remaining: 449ms
285:	learn: 4.4767668	total: 179ms	remaining: 448ms
286:	learn: 4.4760281	total: 180ms	remaining: 447ms
287:	learn: 4.4714524	total: 180ms	remaining: 446ms
288:	learn: 4.4689081	total: 181ms	remaining: 445ms
289:	learn: 4.4661814	total: 181ms	remaining: 444ms
290:	learn: 4.4653482	total: 182ms	remaining: 443ms
291:	learn: 4.4620766	total: 182ms	remaining: 442ms
292:	learn: 4.4569542	total: 183ms	remaining: 442ms
293:	learn: 4.4516329	total: 184ms	remaining: 442ms
294:	learn: 4.4489139	total: 184ms	remaining: 441ms
295:	learn: 4.4441405	total: 185ms	remaining: 440ms
296:	learn: 4.4414895	total: 185ms	remaining: 439ms
297:	learn: 4.4362985	total: 187ms	remaining: 440ms
298:	learn: 4.4309720	total: 187ms	remaining: 439ms
299:	learn: 4.4288697	total: 188ms	remaining: 439ms
300:	learn: 4.4255498	total: 189ms	remaining: 438ms
301:	learn: 4.4207274	total: 189ms	remaining: 437ms
302:	learn: 4.4143469	total: 190ms	remaining: 436ms
303:	learn: 4.4127049	total: 190ms	remaining: 436ms
304:	learn: 4.4081613	total: 191ms	remaining: 436ms
305:	learn: 4.4051642	total: 192ms	remaining: 436ms
306:	learn: 4.4022495	total: 193ms	remaining: 435ms
307:	learn: 4.4002641	total: 193ms	remaining: 434ms
308:	learn: 4.3957465	total: 194ms	remaining: 433ms
309:	learn: 4.3917051	total: 194ms	remaining: 433ms
310:	learn: 4.3874322	total: 195ms	remaining: 432ms
311:	learn: 4.3871944	total: 195ms	remaining: 431ms
312:	learn: 4.3869770	total: 196ms	remaining: 430ms
313:	learn: 4.3864762	total: 197ms	remaining: 430ms
314:	learn: 4.3845844	total: 197ms	remaining: 429ms
315:	learn: 4.3800980	total: 198ms	remaining: 429ms
316:	learn: 4.3772781	total: 199ms	remaining: 428ms
317:	learn: 4.3701822	total: 199ms	remaining: 427ms
318:	learn: 4.3673735	total: 200ms	remaining: 427ms
319:	learn: 4.3619911	total: 201ms	remaining: 426ms
320:	learn: 4.3615180	total: 201ms	remaining: 426ms
321:	learn: 4.3591204	total: 202ms	remaining: 425ms
322:	learn: 4.3564381	total: 202ms	remaining: 424ms
323:	learn: 4.3547483	total: 203ms	remaining: 423ms
324:	learn: 4.3541272	total: 204ms	remaining: 423ms
325:	learn: 4.3526456	total: 204ms	remaining: 422ms
326:	learn: 4.3499073	total: 205ms	remaining: 422ms
327:	learn: 4.3496831	total: 206ms	remaining: 421ms
328:	learn: 4.3484713	total: 206ms	remaining: 421ms
329:	learn: 4.3483357	total: 207ms	remaining: 420ms
330:	learn: 4.3440008	total: 208ms	remaining: 419ms
331:	learn: 4.3395755	total: 208ms	remaining: 419ms
332:	learn: 4.3343157	total: 209ms	remaining: 418ms
333:	learn: 4.3305990	total: 209ms	remaining: 417ms
334:	learn: 4.3268595	total: 210ms	remaining: 417ms
335:	learn: 4.3266545	total: 210ms	remaining: 416ms
336:	learn: 4.3223971	total: 211ms	remaining: 415ms
337:	learn: 4.3201021	total: 211ms	remaining: 414ms
338:	learn: 4.3187620	total: 212ms	remaining: 414ms
339:	learn: 4.3185655	total: 213ms	remaining: 413ms
340:	learn: 4.3140564	total: 214ms	remaining: 413ms
341:	learn: 4.3098693	total: 214ms	remaining: 412ms
342:	learn: 4.3093820	total: 215ms	remaining: 412ms
343:	learn: 4.3038523	total: 216ms	remaining: 411ms
344:	learn: 4.2977300	total: 216ms	remaining: 410ms
345:	learn: 4.2937912	total: 217ms	remaining: 410ms

## Results

In [46]:
res=pd.DataFrame(list(zip(model_list,r2_list,rmse_list)), columns=['Model Name','R2 Score', 'RMSE']).sort_values(['R2 Score'], ascending=False)
res

                                          Model Name  R2 Score      RMSE
2                                            Ridge()  0.877990  5.478806
0                                 LinearRegression()  0.877824  5.482528
7            CatBoostRegressor(loss_function='RMSE')  0.854830  5.976235
5  (DecisionTreeRegressor(max_features=1.0, rando...  0.848376  6.107626
8  (DecisionTreeRegressor(max_depth=3, random_sta...  0.844528  6.184641
6  XGBRegressor(base_score=None, booster=None, ca...  0.836290  6.346378
1                                            Lasso()  0.820027  6.654136
3                              KNeighborsRegressor()  0.793207  7.132741
4                            DecisionTreeRegressor()  0.758901  7.701688